source_path: "data/d-nerf/mutant"
model_path: "outputs/d-nerf/mutant"

downsample: 1.0
densify_until_iter: 8000
warm_up: 3000
iterations: 25000

white_background: True
eval: True
is_blender: True

# DPSR parameters
dpsr_iter: 10000
dpsr_sig: 3.0
grid_res: 288
gaussian_ratio: 1.2
init_density_threshold: 0.0

# Loss weights
mask_loss_weight: 1.0
mesh_img_loss_weight: 1.0
laplacian_loss_weight: 1.0

# Anchoring parameters
use_anchor: 1.0
anchor_iter: 16000
anchor_n_1_bs: 128
anchor_0_1_bs: 128
anchor_search_radius: 0.0015
anchor_interval: 100
