source_path: "data/iphone-captured/tiger"
model_path: "outputs/iphone-captured/tiger"
data_type: "iPhone"

downsample: 1.0
densify_until_iter: 8000
warm_up: 3000
iterations: 25000

white_background: True
eval: True 
is_blender: False

# 3DGS parameters
apperance_lr_init: 0.0008
apperance_lr_final: 0.000008

# DPSR parameters
dpsr_iter: 8000
dpsr_sig: 3.0
grid_res: 288
gaussian_ratio: 1.0
gaussian_center: [-0.25, -0.25, -0.25]
init_density_threshold: 0.0

# Loss weights
mask_loss_weight: 1.0
mesh_img_loss_weight: 1.0
laplacian_loss_weight: 1.0

# Anchoring parameters
use_anchor: 1.0
anchor_iter: 10000
anchor_n_1_bs: 128
anchor_0_1_bs: 128
anchor_search_radius: 0.0005
anchor_interval: 100
